baseURL: "https://jrodal98.github.io/startpage/"
languageCode: en-us
title: Startpage
theme: freshstart

params:
  author: Jacob Rodal
  description: Jacob Rodal Startpage
  favicon: /favicon.ico

  searchEngines:
    - name: Brunnylol
      activated: true
      icon: fas fa-search
      url: https://brunnylol.xyz/search?q=%s

  nav:
    - name: Protonmail
      icon: fas fa-envelope red
      url: https://mail.protonmail.com/

    - name: Facebook
      icon: fab fa-facebook blue
      url: https://facebook.com

    - name: github
      icon: fab fa-github
      url: https://github.com/jrodal98/

  bookmarks:
    - group: dev
      icon: fas fa-code-branch
      items:
        - name: fbpcs
          icon: fab fa-github
          url: https://github.com/facebookresearch/fbpcs/
        - name: nvim
          icon: fab fa-github
          url: https://github.com/jrodal98/nvim
        - name: dotfiles
          icon: fab fa-github
          url: https://github.com/jrodal98/dotfiles
        - name: nvchad
          icon: fab fa-github
          url: https://github.com/nvchad/nvchad

    - group: Pi
      icon: fab fa-raspberry-pi
      items:
        - name: Home
          url: http://192.168.0.104
          icon: fa fa-home

        - name: Jellyfin
          url: http://192.168.0.104:8096
          icon: fa fa-tv

        - name: Transmission
          url: http://192.168.0.104:9091
          icon: fa fa-download

        - name: Syncthing
          url: http://192.168.0.104:8384
          icon: fa fa-cloud

        - name: Pihole
          url: http://192.168.0.199/admin
          icon: fa fa-ban

    - group: Home
      icon: fa fa-home
      items:
        - name: Stackhouse
          url: https://stackhouseapartments.securecafe.com/residentservices/stack-house/home.aspx
          icon: fa fa-home

        - name: WaveG
          url: https://my.wavebroadband.com/
          icon: fa fa-wifi

        - name: Seattle Light
          url: https://login.seattle.gov/#/login
          icon: fa fa-bolt

        - name: Conservice
          url: https://utilitiesinfo.conservice.com/
          icon: fa fa-trash
